BUILD_DIR = priv
C_SRC_DIR = c_src
DEMO_C_SRC_DIR = c_src_demo

SRC = $(C_SRC_DIR)/gpu_nifs.cpp
TARGET = $(BUILD_DIR)/gpu_nifs.so
DEPENDENCIES = $(C_SRC_DIR)/ocl_interface/OCLInterface.cpp
HEADER_DEPENDENCIES = $(C_SRC_DIR)/cldef.hpp $(C_SRC_DIR)/ocl_interface/OCLInterface.hpp

BMP_SRC = $(C_SRC_DIR)/bmp_nifs.cpp
BMP_TARGET = $(BUILD_DIR)/bmp_nifs.so
BMP_DEPENDENCIES = $(C_SRC_DIR)/bmp/BMP.cpp
BMP_HEADER_DEPENDENCIES = $(C_SRC_DIR)/bmp/BMP.hpp

DEMO_SRC = $(DEMO_C_SRC_DIR)/demo_nifs.cpp
DEMO_TARGET = $(BUILD_DIR)/demo_nifs.so
DEMO_DEPENDENCIES = $(DEMO_C_SRC_DIR)/SDL2Interface/SDL2Interface.cpp
DEMO_HEADER_DEPENDENCIES = $(DEMO_C_SRC_DIR)/SDL2Interface/SDL2Interface.hpp
DEMO_LINKFLAGS = -lSDL2

CXX = g++
CXXFLAGS = -shared -fPIC -Wall -Wextra -std=c++17
LINKFLAGS = -lOpenCL

all: $(TARGET)
bmp: $(BUILD_DIR) $(BMP_TARGET)
demo: $(BUILD_DIR) $(DEMO_TARGET)

$(TARGET): $(SRC) $(DEPENDENCIES) $(HEADER_DEPENDENCIES)
	$(CXX) $(CXXFLAGS) $(DEPENDENCIES) $(SRC) -o $(TARGET) $(LINKFLAGS)

$(BMP_TARGET): $(BMP_SRC) $(BMP_DEPENDENCIES) $(BMP_HEADER_DEPENDENCIES)
	$(CXX) $(CXXFLAGS) $(BMP_DEPENDENCIES) $(BMP_SRC) -o $@

$(DEMO_TARGET): $(DEMO_SRC) $(DEMO_DEPENDENCIES) $(DEMO_HEADER_DEPENDENCIES)
	$(CXX) $(CXXFLAGS) $(DEMO_DEPENDENCIES) $(DEMO_SRC) -o $@ $(DEMO_LINKFLAGS)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -rf $(BUILD_DIR)/*.so

.PHONY: all bmp demo clean
